# possible colors: https://xkcd.com/color/rgb/
Fluxes:
  total:
    color: black
    linestyle: '-'
    label: Total Bestfit
  conventional:
    color: black
    label: Conventional
    linestyle: ':'
  conv_norm:
    color: black
    label: Conventional
    linestyle: ':'
  muon:
    color: orange
    label: Muon Background
    linestyle: '--'
  muon_tracks:
    color: orange
    label: Muon Background
    linestyle: '--'
  muon_cscd:
    color: orange
    label: Muon Background
    linestyle: '--'
  muon_norm:
    color: orange
    label: Muon Background
    linestyle: '-.'
  prompt_norm:
    color: black
    label: Prompt (S2.3c + H4a)
    linestyle: '-.'
  prompt:
    color: black
    label: Prompt (S2.3c + H4a)
    linestyle: '-.'
  isotropic:
    color: darkgreen
    label: Isotropic Astro
    linestyle: '-'
  SPL:
    color: darkgreen
    label: SPL only
    linestyle: '-'
  astro_norm:
    color: darkgreen
    label: Isotropic Astro
    linestyle: '-'
  fermi:
    color: xkcd:dull orange
    label: Fermi-$\pi^0$
    mathlabel: \mathrm{Fermi-}\pi^0
    linestyle: '-'
  Fermi:
    color: xkcd:dull orange
    label: Fermi-$\pi^0$
    mathlabel: \mathrm{Fermi-}\pi^0
    linestyle: '-'
  galactic_fermi:
    color: xkcd:dull orange
    label: Fermi-$\pi^0$
    mathlabel: \mathrm{Fermi-}\pi^0
    linestyle: 'densely dashdotdotted'
  KRA_5:
    color: xkcd:deep sea blue
    label: KRA-$\gamma$-5
    mathlabel: \mathrm{KRA-}\gamma -5
    linestyle: 'densely dashed'
  KRA_50:
    color: xkcd:carolina blue
    label: KRA-$\gamma$-50
    mathlabel: \mathrm{KRA-}\gamma -50
    linestyle:  'densely dashdotted'
  AFO-h:
    color: xkcd:dusty red
    label: AFO-h
    linestyle: '-'
  AFO-r:
    color: xkcd:dusty red
    label: AFO-r
    linestyle: '--'
  FM-const:
    color: xkcd:purplish grey
    label: FM-const.
    mathlabel: \mathrm{FM-const.}
    linestyle: '-.'
  FM-Const:
    color: xkcd:purplish grey
    label: FM-const.
    mathlabel: \mathrm{FM-const.}
    linestyle: '-.'
  FM_const:
    color: xkcd:purplish grey
    label: FM-const.
    mathlabel: \mathrm{FM-const.}
    linestyle: '-.'
  FM-SNR:
    color: darkgrey
    label: FM-SNR
    mathlabel: \mathrm{FM-SNR}
    linestyle: ':'
  FM_SNR:
    color: darkgrey
    label: FM-SNR
    mathlabel: \mathrm{FM-SNR}
    linestyle: ':'
  CRINGE_full:
    color: xkcd:violet red
    label: CRINGE-full
    mathlabel: \mathrm{CRINGE-full}
    linestyle: '-'
  SMW:
    color: xkcd:dusty red
    label: CRINGE-diffuse
    mathlabel: \mathrm{CRINGE-diffuse}
    linestyle: '-'
  CRINGE_diffuse:
    color: xkcd:dusty red
    label: CRINGE-diffuse
    mathlabel: \mathrm{CRINGE-diffuse}
    linestyle: '-'
  Cringe_diffuse:
    color: xkcd:dusty red
    label: CRINGE-diffuse
    mathlabel: \mathrm{CRINGE-diffuse}
    linestyle: '-'
  cringe_diffuse:
    color: xkcd:dusty red
    label: CRINGE-diffuse
    mathlabel: \mathrm{CRINGE-diffuse}
    linestyle: '-'
  CringeFITS:
    color: xkcd:dusty red
    label: CRINGE-diffuse
    mathlabel: \mathrm{CRINGE-diffuse}
    linestyle: '-'
  CRINGE_unresolved:
    color: [1.0, 0.5098039215686274, 0.2549019607843137]
    label: CRINGE-unresolved
    mathlabel: \mathrm{CRINGE-unresolved}
    linestyle: ':'
  CRINGE_unresolved:
    color: [1.0, 0.5098039215686274, 0.2549019607843137]
    label: CRINGE-unresolved
    mathlabel: \mathrm{CRINGE-unresolved}
    linestyle: ':'
  Unresolved:
    color: [1.0, 0.5098039215686274, 0.2549019607843137]
    label: CRINGE-unresolved
    mathlabel: \mathrm{CRINGE-unresolved}
    linestyle: ':'
  Cygnus:
    color: xkcd:dark teal
    label: Cygnus
    mathlabel: \mathrm{Cygnus}
    linestyle: '-.'
  cygnus:
    color: xkcd:dark teal
    label: Cygnus
    mathlabel: \mathrm{Cygnus}
    linestyle: '-.'

Parameters:
  CR_grad:
      color: '#bcbd22'
      label: CR Model Interp.
      linestyle: -.
      ylims:
      - 0
      - 10
      xlims:
      - -1
      - 2
  delta_gamma:
      color: '#ff7f0e'
      label: CR $\Delta \gamma$
      linestyle: -.
      ylims:
      - 0
      - 10
      xlims:
      - -0.15
      - 0.15
  conv_norm:
        color: royalblue
        label: $\Phi_{\mathrm{Conventional}}$
        linestyle: '-'
        ylims:
        - 0
        - 10
        xlims:
        - 0.85
        - 1.15
        # - 0.6
        # - 1.3
  muon_norm:
      color: cornflowerblue
      label: $\Phi_{\mu, \mathrm{Tracks}}$
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 2.5
  muongun_norm:
      color: cornflowerblue
      label: $\Phi_{\mu, \mathrm{Cscd.}}$
      linestyle: '-.'
      ylims:
      - 0
      - 10
      xlims:
      - 0.9
      - 1.1
  prompt_norm:
      color: turquoise
      label: $\Phi_{\mathrm{Prompt}}$
      linestyle: '-.'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 6
  gamma_astro:
      color: darkviolet
      label: $\gamma_{\mathrm{isotropic}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 2.2
      - 2.8
  gamma_1:
      color: darkviolet
      label: $\gamma_{\mathrm{1, isotropic}}$
      linestyle: '-.'
      ylims:
      - 0
      - 5
      xlims:
      - 1
      - 2.0
  gamma_2:
      color: darkviolet
      label: $\gamma_{\mathrm{2, isotropic}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 2.5
      - 3
  e_break:
      color: midnightblue
      label: $E_{\mathrm{break}}$
      linestyle: '-.'
      ylims:
      - 0
      - 10
      xlims:
      - 4
      - 5
  astro_norm:
      color: blue
      label: $\Phi_{\mathrm{isotropic}}$
      linestyle: '--'
      ylims:
      - 0
      - 10
      xlims:
      - 0.5
      - 3.0
  cutoff_astro:
      color: steelblue
      label: $\log_{10}(E_{\mathrm{cutoff}} / \mathrm{GeV})$
      linestyle: '-.'
      ylims:
      - 0
      - 10
      xlims:
      - 5
      - 7
  astro_parabola_norm:
      color: '#8ebbfd'
      label: Log-Parabola Norm
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 1
      - 3
  astro_parabola_a:
      color: '#7a378b'
      label: Log-Parabola $\alpha$
      linestyle: '-.'
      ylims:
      - 0
      - 10
      xlims:
      - 1.5
      - 3
  astro_parabola_b:
      color: '#9d1b71'
      label: Log-Parabola $\beta$
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 1
  galactic_norm:
      color: darkblue
      label: $\Psi_{\mathrm{galactic}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  cringe_norm:
      color: xkcd:dusty red
      label: $\Psi_{\mathrm{CRINGE, diffuse}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  cringefits_norm:
      color: xkcd:dusty red
      label: $\Psi_{\mathrm{CRINGE, diffuse}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5 
  cringefits_and_unresolved_norm:
      color: xkcd:violet red
      label: $\Psi_{\mathrm{CRINGE, full}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  cringe_diffuse_norm:
      color: xkcd:dusty red
      label: $\Psi_{\mathrm{CRINGE, diffuse}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  unresolved_norm:
      color: [1.0, 0.5098039215686274, 0.2549019607843137]
      label: $\Psi_{\mathrm{CRINGE, unresolved}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  cygnus_norm:
      color: xkcd:dark teal
      label: $\Psi_{\mathrm{Cygnus}}$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 10
  gamma_galactic:
      color: darkblue
      label: $\gamma_{\mathrm{galactic}}$
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - 0
      - 5
  barr_h:
      color: firebrick
      label: Barr $H$
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - -0.1
      - 0.1
  barr_w:
      color: firebrick
      label: Barr $W$
      linestyle: --
      ylims:
      - 0
      - 10
      xlims:
      - -0.5
      - 0.5
  barr_y:
      color: firebrick
      label: Barr $Y$
      linestyle: -.
      ylims:
      - 0
      - 10
      xlims:
      - -0.2
      - 0.2
  barr_z:
      color: firebrick
      label: Barr $Z$
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - -0.3
      - 0.2
  dom_eff:
      color: forestgreen
      label: Opt. Efficiency
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - 0.98
      - 1.02
  ice_abs:
      color: forestgreen
      label: Ice Absorption
      linestyle: --
      ylims:
      - 0
      - 10
      xlims:
      - 0.97
      - 1.03
  ice_holep0:
      color: forestgreen
      label: Ice Hole $p_0$
      linestyle: '-'
      ylims:
      - 0
      - 1500
      xlims:
      - -0.5
      - 0.5
  ice_holep1:
      color: forestgreen
      label: Ice Hole $p_1$
      linestyle: ':'
      ylims:
      - 0
      - 10
      xlims:
      - -0.07
      - -0.01
  ice_scat:
      color: forestgreen
      label: Ice Scattering
      linestyle: -.
      ylims:
      - 0
      - 10
      xlims:
      - 0.97
      - 1.03
  effective_veto:
      color: grey
      label: Effective Veto
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - -1.5
      - 1.5
  cscd_piece1:
      color: grey
      label: CSCD Piece 1
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece2:
      color: grey
      label: CSCD Piece 2
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece3:
      color: grey
      label: CSCD Piece 3
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece4:
      color: grey
      label: CSCD Piece 4
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece5:
      color: grey
      label: CSCD Piece 5
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece6:
      color: grey
      label: CSCD Piece 6
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece7:
      color: grey
      label: CSCD Piece 7
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece8:
      color: grey
      label: CSCD Piece 8
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece9:
      color: grey
      label: CSCD Piece 9
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece10:
      color: grey
      label: CSCD Piece 10
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece10:
      color: grey
      label: CSCD Piece 10
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece10:
      color: grey
      label: CSCD Piece 10
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece11:
      color: grey
      label: CSCD Piece 11
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece12:
      color: grey
      label: CSCD Piece 12
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece13:
      color: grey
      label: CSCD Piece 13
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece14:
      color: grey
      label: CSCD Piece 14
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  cscd_piece15:
      color: grey
      label: CSCD Piece 15
      linestyle: '-'
      ylims:
      - 0
      - 10
      xlims:
      - 0.0
      - 3.0
  llh:
      color: black
      label: $-\log(\mathcal{L})$
      linestyle: '-'
      ylims:
      - 0
      - 10
